---
language: erlang

env:
  global:
    - KERL_BUILD_BACKEND=git
jobs:
  include:
    
    #   dist: xenial
    #   group: edge
    #   name: xenial
    - dist: bionic
      name: bionic
    - dist: focal
      name: focal
    - dist: jammy
      name: jammy
    - dist: noble
      name: noble

    - dist: bionic
      arch: ppc64le
      name: bionic-ppc64le
    - dist: focal
      arch: ppc64le
      name: focal-ppc64le
    - dist: jammy
      arch: ppc64le
      name: jammy-ppc64le
    - dist: noble
      arch: ppc64le
      name: noble-ppc64le

    - dist: bionic
      arch: arm64
      name: bionic-arm64
    - dist: focal
      arch: arm64
      name: focal-arm64
    - dist: jammy
      arch: arm64
      name: jammy-arm64
    - dist: noble
      arch: arm64
      name: noble-arm64

    # - dist: xenial
    #   arch: s390x
    #   name: s390x-xenial
    - dist: bionic
      arch: s390x
      name: bionic-s390x
    - dist: focal
      arch: s390x
      name: focal-s390x
    - dist: jammy
      arch: s390x
      name: jammy-s390x
    - dist: noble
      arch: s390x
      name: noble-s390x     

before_install:
  - export OS_NAME=$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")
  - export RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - export TARGET_DIR=${TRAVIS_BUILD_DIR}/${OS_NAME}/${RELEASE}/$(uname -m)
  - export VERSION=${VERSION:-21.2}
  - mkdir -p ${TARGET_DIR}

install:
  - |
    if ! command -v kerl >&/dev/null; then
      curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
      chmod +x kerl
      sudo mv kerl /usr/local/bin/kerl
    fi
    sudo curl -o `which kerl` https://raw.githubusercontent.com/yrashk/kerl/master/kerl

script: ./bin/compile

after_success: ./bin/archive

addons:
  artifacts:
    paths:
      - "${OS_NAME}"
    target_paths:
      - "/binaries/${OS_NAME}/${LSB_RELEASE}/${ARCH}"
